development:
  adapter:   postgresql
  encoding:  unicode
  host:      localhost
  username:  postgres
  pool:      5
  database:  gk_development

test:
  adapter:   postgresql
  encoding:  unicode
  host:      localhost
  username:  postgres
  pool:      5
  database:  gk_test

production:
  adapter:   postgresql
  encoding:  unicode
  host:      localhost
  username:  postgres
  pool:      5
  database:  gk_production
